### ISSUE TITLE
When moving Parameters on a Shape, Multiple shapes appear.

### ISSUE THREAD

**Issue by jacobgoldenart** [haschdl/pLaunchController#4]
Hello, Thanks for creating this. It's a great help. I've managed to make a version that works with the Launch Control XL MK2. I've successfully mapped all of the knobs, faders, and buttons and I'm able to change parameters on the fly with the sketch running. Here is an issue I've found.
When assigning knobs to control the parameters the width and height of a  rect(), for instance, I can expand the width or the height of the rect by turning the knob up in value (as expected), but when I turn the knob down again to a lower value it resizes the height or width but it leaves a lot of rectangles along the way. (see the animated gif for an example. I believe it is doing this because the draw function is creating a 'new' rect() with every frame. Is there a way to simply change the dimensions of the rect so it always looks like only one rect is in the sketch? I hope that makes sense and thanks again for your contribution.
![lcXL-DrawRect](https://user-images.githubusercontent.com/77907191/106321692-81745c80-6229-11eb-835f-42dceaa477da.gif)
`import pLaunchController.*;
float a1, a2, a3, a4, a5, a6, a7, a8;
LaunchController controller;

void setup() {
   size(900, 900, P2D);
   background(255);
  // noLoop(); // Tried to use no Loop as I'am mostly making 2D static artwork
   
try {
controller = new LaunchController(this);

    //Hi Knobs A1 - A8
    controller.getKnob(KNOBS.KNOB_1_HIGH).range(50,400).defaultValue(50).variable("a1");
    controller.getKnob(KNOBS.KNOB_2_HIGH).range(50,400).defaultValue(50).variable("a2");
    controller.getKnob(KNOBS.KNOB_3_HIGH).range(0,10).defaultValue(10).variable("a3");
    controller.getKnob(KNOBS.KNOB_4_HIGH).range(0,10).defaultValue(10).variable("a4");
    controller.getKnob(KNOBS.KNOB_5_HIGH).range(0,10).defaultValue(10).variable("a5");
    controller.getKnob(KNOBS.KNOB_6_HIGH).range(0,10).defaultValue(10).variable("a6");
    controller.getKnob(KNOBS.KNOB_5_HIGH).range(0,10).defaultValue(10).variable("a7");
    controller.getKnob(KNOBS.KNOB_6_HIGH).range(0,10).defaultValue(10).variable("a8");
    
  }
 catch(Exception e) {
    println("Unfortunately we could not detect that Launch Control is connected to this computer :(");
  } 
   stroke(0);
}

// Attaching Knob 1 and 2 to width and height
void draw() { 
  rect(0, 200, a2, a1); 
}
}
`
[lcXL-sketch.txt](https://github.com/haschdl/pLaunchController/files/5896068/lcXL-sketch.txt)

**Comment by jacobgoldenart** [comment]
Oh my gosh, this was an easy solution; ) I realized if I place background(0) in the draw function it works as expected : 0
This makes sense since I was drawing the rect with every frame, I will need to draw the background as well!

**Comment by haschdl** [comment]
hi @jacobgoldenart I'm glad you found the library useful! I haven't updated it in quite a while so it is possible you find something not working 100% - feel free to reach out if you find a bug. It sounds like you found out the solution! I'll close this issue for now.  If you share something on instagram you can also tag me or the library, it would be nice to have more people using it. https://www.instagram.com/h.scheidl/
